blank_issues_enabled: false
contact_links:
  - name: 📚 Issue Template Guide
    url: https://github.com/thefewminutes/skills-expand-your-team-with-copilot/blob/main/docs/issue-templates-guide.md
    about: Learn how to use issue templates effectively for Copilot coding agents
  - name: 📖 Documentation
    url: https://github.com/thefewminutes/skills-expand-your-team-with-copilot/tree/main/docs
    about: Check the documentation for development guides and help
  - name: 💬 Discussion
    url: https://github.com/thefewminutes/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community